[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[main]]
  identifier = "docs"
  name = "Docs"
  pageRef = "#"
  weight = 25

[[main]]
  parent = "docs"
  name = "project-1"
  pageRef = "docs/sample-project"
  weight = 10

[[main]]
  parent = "docs"
  name = "project-2"
  pageRef = "docs/another-project"
  weight = 20

[[main]]
  name = "About"
  pageRef = "/tags"
  weight = 30

[[docs]]
  identifier = "docs"
  name = "Docs"
  pageRef = "docs"
  weight = 100

[[docs]]
  parent = "docs"
  name = "p1"
  pageRef = "sample-project"
  weight = 10

[[docs]]
  parent = "docs"
  name = "p2"
  pageRef = "another-project"
  weight = 20

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  pageRef = "/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation